apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-app
  template:
    metadata:
      labels:
        app: ui-app
    spec:
      containers:
      - name: ui-app
        image: chonku/jffs-ui:v1.7
        envFrom:
          - configMapRef:
              name: ui-app-config
        imagePullPolicy: Always
        ports:
        - containerPort: 3000