services:
  jffs-api-gateway:
    container_name: jffs-api-gateway
    depends_on:
      - jffs-ui
      - jffs-backend
    build:
      context: jffs-api-gateway
    environment:
      - JFFS_BACKEND_HOST=jffs-backend
      - JFFS_BACKEND_PORT=8080
      - JFFS_UI_HOST=jffs-ui
      - JFFS_UI_PORT=3000
    command: [ nginx, '-g', 'daemon off;' ]
    networks:
      - AppNetwork
    ports:
      - "80:80"
      - "443:443"

  jffs-ui:
    container_name: jffs-ui
    build:
      context: jffs-ui
    depends_on:
      - jffs-backend
    networks:
      - AppNetwork
    ports:
      - "3000:3000"

  jffs-backend:
    container_name: jffs-backend
    networks:
      - AppNetwork
    depends_on:
      - database
    build:
      context: jffs-backend
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - "DB_USER=root"
      - "DB_PWD=example"
      - "APP_NAME=testDB"
      - "DB_NAME=testDB"
      - "DB_HOST=database"
      - "DB_SCHEME=mongodb"

  database:
    image: mongo:7.0
    container_name: database
    networks:
      - AppNetwork
      - AdminNetwork
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=example"
      - "MONGO_INITDB_DATABASE=testDB"

  jffs-admin-api-gateway:
    container_name: jffs-admin-api-gateway
    depends_on:
      - jffs-admin-ui
      - jffs-admin-backend
    build:
      context: jffs-admin-api-gateway
    environment:
      - JFFS_ADMIN_BACKEND_HOST=jffs-admin-backend
      - JFFS_ADMIN_BACKEND_PORT=9090
      - JFFS_ADMIN_UI_HOST=jffs-admin-ui
      - JFFS_ADMIN_UI_PORT=3000
    command: [ nginx, '-g', 'daemon off;' ]
    networks:
      - AdminNetwork
    ports:
      - "8060:80"
      - "8443:443"

  jffs-admin-backend:
    container_name: jffs-admin-backend
    depends_on:
      - database
    networks:
      - AdminNetwork
    build:
      context: jffs-admin-backend
    ports:
      - "9090:9090"
      - "9091:9091"
    environment:
      - "DB_USER=root"
      - "DB_PWD=example"
      - "APP_NAME=testDB"
      - "DB_NAME=testDB"
      - "DB_HOST=database:27017"
      - "DB_SCHEME=mongodb"

  jffs-admin-ui:
    container_name: jffs-admin-ui
    build:
      context: jffs-admin-ui
    depends_on:
      - jffs-admin-backend
    ports:
      - "3001:3000"
    networks:
      - AdminNetwork

networks:
  AppNetwork:
  AdminNetwork:
