services:
  jffs-admin-api-gateway:
    container_name: jffs-admin-api-gateway
    depends_on:
      - jffs-admin-ui
      - jffs-admin-backend
    build:
      context: jffs-admin-api-gateway
    environment:
      - JFFS_ADMIN_BACKEND_HOST=jffs-admin-backend
      - JFFS_ADMIN_BACKEND_PORT=9090
      - JFFS_ADMIN_UI_HOST=jffs-admin-ui
      - JFFS_ADMIN_UI_PORT=3000
    command: [ nginx, '-g', 'daemon off;' ]
    networks:
      - AdminNetwork
    ports:
      - "8060:80"
      - "8443:443"

  jffs-admin-backend:
    container_name: jffs-admin-backend
    networks:
      - AdminNetwork
    build:
      context: jffs-admin-backend
    ports:
      - "9090:9090"
      - "9091:9091"
    environment:
      - "DB_USER=root"
      - "DB_PWD=example"
      - "APP_NAME=testDB"
      - "DB_NAME=testDB"
      - "DB_HOST=database"
      - "DB_SCHEME=mongodb"

  jffs-admin-ui:
    container_name: jffs-admin-ui
    build:
      context: jffs-admin-ui
    depends_on:
      - jffs-admin-backend
    ports:
      - "3001:3000"
    networks:
      - AdminNetwork

networks:
  AdminNetwork:
