spring:
  active: prod

server:
  port: ${SERVER_PORT:9090}
  servlet:
    context-path: /admin

management:
  server.port: ${SERVER_MGT_PORT:9091}
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure.include: health, status, mappings, metrics, configprops
      path-mapping:
        configprops: config

database:
  username: ${DB_USER:vocab_data}
  password: ${DB_PWD:vocab_data}
  appName: ${APP_NAME:vocab_app}
  dbName: ${DB_NAME:vocab_db}
  host: ${DB_HOST:vocab_host}
  scheme: ${DB_SCHEME:mongodb+srv}

graphql:
  servlet:
    enabled: true
    mapping: /graphql
    corsEnabled: true
    cors:
      allowed-methods: GET, HEAD, POST
    async-mode-enabled: true

graphiql:
  mapping: /graphiql
  static:
    basePath: /
  enabled: true
  pageTitle: GraphiQL