---

- name: Remote Dev
  hosts: localhost
  vars:
    kube_config: .kube/k8s-1-29-1-do-0-lon1-1710889039000-kubeconfig.yaml
  connection: local
  tasks:

    - name: account $HOME
      shell: "echo $HOME"
      register: account_homedir
      changed_when: false
      check_mode: no

    - name: Create UI config map
      shell: "kubectl --kubeconfig={{ account_homedir.stdout }}/{{ vars.kube_config }} create configmap ui-app-config --from-env-file={{ playbook_dir }}/ui/properties/ui-app-dev.properties"
      register: out

    - name: Create UI app backend deployment
      shell: "kubectl --kubeconfig={{ account_homedir.stdout }}/{{ vars.kube_config }} apply -f {{ playbook_dir }}/ui/deployment.yml"
      register: out

    - name: Expose UI app service
      shell: "kubectl --kubeconfig={{ account_homedir.stdout }}/{{ vars.kube_config }} expose deployment ui-app-deployment --type=NodePort --name=ui-app-service --port 80 --target-port 3000"
      register: out

    - name: Creating the Nginx Ingress Controller Kubernetes resources
      shell: "kubectl --kubeconfig={{ account_homedir.stdout }}/{{ vars.kube_config }} apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.1/deploy/static/provider/do/deploy.yaml"

    - debug: var=out.stdout_lines




    
