spring:
  active: prod
  webflux:
    base-path: /api

server:
  port: ${SERVER_PORT:9090}

management:
  server.port: ${SERVER_MGT_PORT:9091}
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure.include: health, mappings, metrics, prometheus, configprops
      path-mapping:
        configprops: config

oanda:
  host: ${OANDA_HOST:https://api-fxpractice.oanda.com}
  apikey: ${OANDA_API_KEY:key}