global:
  scrape_interval: 30s
  scrape_timeout: 5s
scrape_configs:
  - job_name: JFFS_BACKEND_JOB
    static_configs:
      - targets: ['localhost:8081']
        labels:
          group: 'production'
    sample_limit: 10000
    metrics_path: /actuator/prometheus