spring:
  active: prod

server:
  port: 8080
  servlet:
    context-path: /api

management:
  server.port: ${SERVER_MGT_PORT:8081}
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure.include: health, mappings, metrics, configprops
      path-mapping:
        configprops: config