---

- name: Dev
  hosts: localhost
  connection: local
  tasks:

    - name: Register a variable, ignore errors and continue
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.env', 'DEPLOY_TYPE')}}"
      register: result
      ignore_errors: true

    - include_tasks: build_and_tag_image.yml

    # - include_tasks: local-dev/delete_local_dev.yml

    # - include_tasks: local-dev/create_local_dev.yml

    # - include_tasks: test_local_dev.yml

    - include_tasks: remote-dev/delete_remote_dev.yml
      when: result.msg == 'REMOTE'

    - include_tasks: remote-dev/pipeline.yml
      when: result.msg == 'REMOTE'
