CREATE TABLE CANDLE_S5(
    CANDLE_S5_ID VARCHAR(32) PRIMARY KEY,
    INSTRUMENT VARCHAR(10),
    RECORDED_TIMESTAMP VARCHAR(31),
    PRICE_OPEN VARCHAR(15),
    PRICE_HIGH VARCHAR(15),
    PRICE_LOW VARCHAR(15),
    PRICE_CLOSE VARCHAR(15)
);

CREATE TABLE CANDLE_S10(
    CANDLE_S10_ID VARCHAR(32) PRIMARY KEY,
    INSTRUMENT VARCHAR(10),
    RECORDED_TIMESTAMP VARCHAR(31),
    PRICE_OPEN VARCHAR(15),
    PRICE_HIGH VARCHAR(15),
    PRICE_LOW VARCHAR(15),
    PRICE_CLOSE VARCHAR(15)
);